### ISSUE TITLE
The language is useless.

### ISSUE THREAD

**Issue by SY-Xuan** [983632847/All-in-One#6]
In your implementations, the [CLS] token of the BertEmbedding is used. Without any attention operation, the [CLS] token of the BertEmbedding cannot take any information about the input description. In other words, the language modal is useless in the current implementations. Do I have any misunderstanding here?

**Comment by 983632847** [comment]
We just use BertEmbedding as the tokenizer. During the training phase, the [tokenizer](https://github.com/983632847/All-in-One/blob/main/lib/models/ostrack/ostrack.py) can be updated and the mean token can be used. We also found that using only the trained visual branch for inference can achieve good results, due to the large amount of ambiguity in language prompts.

**Comment by SY-Xuan** [comment]
In your implementations, whatever the input description is, the output of the [CLS] will be the same. Therefore, I don`t think the performance improvement is related to the adding of the language description.

**Comment by wjh-scut** [comment]
> In your implementations, whatever the input description is, the output of the [CLS] will be the same. Therefore, I don`t think the performance improvement is related to the adding of the language description.

我也有相同的疑问，请问您弄明白这个问题了吗？ @SY-Xuan
